# Site settings
title: Stuff With Evan
email: oakeef@gmail.com
description: Evan's blog and portfolio site.
twitter_username: stuffwithevan
github_username:  oakeef
paginate: 3
gems:
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: pretty
