# Site settings
title: Stuff With Evan
email: oakeef@gmail.com
description: Evan's blog and portfolio site.
url: "http://stuffwithevan.com" # the base hostname & protocol for your site
twitter_username: stuffwithevan
github_username:  oakeef
paginate: 3
gems:
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: pretty