# Site settings
title: Stuff With Evan
email: oakeef@gmail.com
description: Stuff with Evan.
url: http://stuffwithevan.com
twitter_username: stuffwithevan
github_username:  oakeef
paginate: 3
gems:
  - jekyll-paginate

# Build settings
markdown: kramdown
permalink: pretty
